openapi: 3.1.0
info:
  title: Open Payments
  version: "1.0"
  license:
    name: Apache 2.0
    identifier: Apache-2.0
  description: >-
    The Open Payments API is a simple REST API with 4 resource types:
    **account**, **account holder**, **incoming payment** and **outgoing
    payment**.  


    The *service endpoint* for the API is always the URL of the account resource
    and all other resources are sub-resources of the account.  


    All resource and collection resource representations use JSON and the
    media-type `application/json`.  


    The `account` resource has two collections of sub-resources and a single
    **account holder** sub-resource:   

    1. `/incoming-payments` contains the **incoming payment** sub-resources  

    2. `/outgoing-payments` contains the **outgoing payment** sub-resources  

    3. `/holder` contains the **outgoing payment** sub-resources  


    Access to resources and permission to execute the methods exposed by the API
    is determined by the grants given to the client represented by an access
    token used in API requests.
  summary: An API for open access to financial accounts to send and receive payments.
servers:
  - url: "https://openpayments.guide/alice"
    description: alice
  - url: "https://openpayments.guide/bob"
    description: bob
paths:
  /:
    get:
      summary: Get a Payment Pointer
      tags: []
      responses:
        "200":
          description: Account Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/account"
              examples:
                Get account for $openpayments.example:
                  value:
                    id: "https://openpayments.example"
        "404":
          description: Account Not Found
      operationId: get-public-account
      description: >-
        Retrieve the public information of the account represented by the
        Payment Pointer.


        This end-point should be open to anonymous requests as it allows clients
        to verify a Payment Pointer URL and get the basic information required
        to construct new transactions and discover the grant request URL.


        The content should be slow changing and cacheable for long periods.
        Servers SHOULD use cache control headers.
      security: []
  /incoming-payments:
    post:
      summary: Create an Incoming Payment
      tags: []
      operationId: create-incoming-payment
      responses:
        "201":
          description: Incoming Payment Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/incoming-payment"
              examples:
                New Incoming Payment for $25:
                  value:
                    id: "http://openpayments.example/incoming-payments/87562464512"
                    accountId: "http://openpayments.example"
                    state: completed
                    incomingAmount:
                      amount: 2500
                      assetCode: USD
                      assetScale: 2
                    receivedAmount:
                      amount: 0
                      assetCode: USD
                      assetScale: 2
                    expiresAt: "2022-02-03T23:20:50.52Z"
                    externalRef: INV2022-02-0137
                    receiptsEnabled: true
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                incomingAmount:
                  $ref: "#/components/schemas/amount"
                expiresAt:
                  type: string
                  description: >-
                    The date and time when payments into the incoming payment
                    must no longer be accepted.
                  format: date-time
                  writeOnly: true
                description:
                  type: string
                  description: >-
                    Human readable description of the incoming payment that will
                    be visible to the account holder.
                externalRef:
                  type: string
                  description: >-
                    A reference that can be used by external systems to
                    reconcile this payment with their systems. E.g. An invoice
                    number. (Optional)
                receiptsEnabled:
                  type: boolean
                  description: >-
                    True if the client wants the receiving account provider to
                    generate receipts.
            examples:
              Create incoming payment for $25 to pay invoice INV2022-02-0137:
                value:
                  incomingAmount:
                    amount: 2500
                    assetCode: USD
                    assetScale: 2
                  externalRef: INV2022-02-0137
        description: >-
          A subset of the incoming payments schema is accepted as input to
          create a new incoming payment.


          If provided, the `incomingAmount` must use the same `assetCode` and
          `assetScale` as the account.
      description: >-
        A client MUST create an **incoming payment** resource before it is
        possible to send any payments to the account. 


        All of the input parameters are _optional_.
    get:
      summary: List Incoming Payments
      operationId: list-incoming-payments
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/incoming-payment"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
      description: List all incoming payments on the account
      parameters: []
  /outgoing-payments:
    post:
      summary: Create an Outgoing Payment
      tags: []
      operationId: create-outgoing-payment
      responses:
        "201":
          description: Outgoing Payment Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/outgoing-payment"
              examples:
                New Fixed Send Outgoing Payment for $25:
                  value:
                    id: >-
                      https://openpayments.example/outgoing-payments/gwe867t2frof
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
      requestBody:
        content:
          application/json:
            examples:
              ? Create fixed-send-amount outgoing payment for $25 to pay invoice INV2022-02-0137
              : value:
                  receivingAccount: "https://openpayments.example"
                  sendAmount:
                    amount: 2500
                  externalRef: INV2022-02-0137
              ? Create fixed-receive-amount outgoing payment for $25 to pay invoice INV2022-02-0137
              : value:
                  receivingAccount: "https://openpayments.example"
                  receiveAmount:
                    amount: 2500
                  externalRef: INV2022-02-0137
            schema:
              type: object
              properties:
                authorized:
                  type: boolean
                  description: Indicates if the payment is authorized to begin processing.
                  default: false
                receivingAccount:
                  type: string
                  format: uri
                  description: The URL of the account that is being paid.
                receivingPayment:
                  type: string
                  format: uri
                  description: The URL of the incoming payment that is being paid.
                receiveAmount:
                  $ref: "#/components/schemas/amount"
                sendAmount:
                  $ref: "#/components/schemas/amount"
                fundsAvailable:
                  type: boolean
                  description: >-
                    Indicates that there are funds available in the underlying
                    account to complete this payment. This is not a guarantee
                    they will still be available when the payment is attempted
                    but it is a good indicator to a client that it should
                    attempt to authorize the payment.
                  readOnly: true
                expiresAt:
                  type: string
                  description: >-
                    The date and time when the calculated `sendAmount` is no
                    longer valid.
                  readOnly: true
                description:
                  type: string
                  description: >-
                    Human readable description of the outgoing payment that will
                    be visible to the account holder and shared with the
                    receiver.
                externalRef:
                  type: string
                  description: >-
                    A reference that can be used by external systems to
                    reconcile this payment with their systems. E.g. An invoice
                    number. (Optional)
                receiptsEnabled:
                  type: boolean
                  description: True if the underlying STREAM has receipts enabled.
        description: >-
          A subset of the outgoing payments schema is accepted as input to
          create a new outgoing payment.


          If provided, the `sendAmount` must use the same `assetCode` and
          `assetScale` as the account.
      description: >-
        An **outgoing payment** is a sub-resource of an account. It represents a
        payment from the account.
    description: Create a new outgoing payment at the account.
    get:
      summary: List Outgoing Payments
      operationId: list-outgoing-payments
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/outgoing-payment"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
      description: List all outgoing payments on the account
      parameters: []
  "/incoming-payments/{id}":
    get:
      summary: Get an Incoming Payment
      tags: []
      operationId: get-incoming-payment
      responses:
        "200":
          description: Incoming Payment Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/incoming-payment"
              examples:
                Incoming Payment for $25 with $12.34 received so far:
                  value:
                    id: >-
                      https://openpayments.example/incoming-payments/gwe867t2frof
                    accountId: "http://openpayments.example"
                    state: processing
                    incomingAmount:
                      amount: 2500
                      assetCode: USD
                      assetScale: 2
                    receivedAmount:
                      amount: 1234
                      assetCode: USD
                      assetScale: 2
                    expiresAt: "2022-04-12T23:20:50.52Z"
                    description: Thanks for the flowers!
                    externalRef: INV-12876
                    ilpAddress: g.ilp.iwuyge987y.98y08y
                    sharedSecret: 6jR5iNIVRvqeasJeCty6C+YB5X9FhSOUPCL/5nha5Vs=
                    receiptsEnabled: true
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          description: Incoming Payment Not Found
      description: >-
        A client can fetch the latest state of an incoming payment to determine
        the amount received into the account.
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Incoming Payment identifier
    put:
      summary: Update an Incoming Payment
      operationId: update-incoming-payment
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/incoming-payment"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          description: Incoming Payment Not Found
      description: >-
        A client with the appropriate permissions MAY update the state of an
        **incoming payment** to `completed` if it is in a state of `pending` or
        `processing`.


        This indicates to the receiving account provider that it can begin any
        post processing of the payment such as generating account statements or
        notifying the account holder of the completed payment.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                state:
                  type: string
                  example: completed
                  enum:
                    - completed
            examples:
              Complete Incoming Payment:
                value:
                  state: completed
        description: Update the state of the incoming payment to `completed`.
  "/outgoing-payments/{id}":
    get:
      summary: Get an Outgoing Payment
      tags: []
      operationId: get-outgoing-payment
      responses:
        "200":
          description: Outgoing Payment Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/outgoing-payment"
              examples:
                Outgoing Payment with a fixed send amount of $25:
                  value:
                    id: >-
                      https://openpayments.example/outgoing-payments/gwe867t2frof
                    accountId: "http://openpayments.example"
                    state: processing
                    authorized: true
                    receivingPayment: "http://openpayments.example/incoming-payments/68gq6t97qwf"
                    sendAmount:
                      amount: 2500
                      assetCode: USD
                      assetScale: 2
                    receiveAmount:
                      amount: 2198
                      assetCode: EUR
                      assetScale: 2
                    fundsAvailable: true
                    expiresAt: "2022-04-12T23:20:50.52Z"
                    description: Thanks for the flowers!
                    externalRef: INV-12876
                    receiptsEnabled: true
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          description: Incoming Payment Not Found
      description: A client can fetch the latest state of an outgoing payment.
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Incoming Payment identifier
    put:
      summary: Update an Outgoing Payment
      operationId: update-outgoing-payment
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/outgoing-payment"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          description: Outgoing Payment Not Found
      description: >-
        A client with the appropriate permissions MAY update an **outgoing
        payment** to either change the amount that was originally requested or
        authorize the payment.


        To authorize the payment the client updates the value of `authorized` to
        `true`.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                state:
                  type: string
                  example: completed
                  enum:
                    - completed
            examples:
              Authorize Outgoing Payment:
                value:
                  authorized: true
              Update Send Amount:
                value:
                  sendAmount:
                    amount: 2500
              Update Receive Amount:
                value:
                  receiveAmount:
                    amount: 512
                    assetCode: EUR
                    assetScale: 2
        description: Update the state of the incoming payment to `completed`.
components:
  schemas:
    account:
      title: Account
      type: object
      description: >-
        An **account** resource is the root of the API and contains the public
        details of the financial account represented by the Payment Pointer that
        is also the service endpoint URL.
      properties:
        id:
          type: string
          format: uri
          description: The URL identifying the incoming payment.
          readOnly: true
        publicName:
          type: string
          description: >-
            A public name for the account. This should be set by the account
            holder with their provider to provide a hint to counterparties as to
            the identity of the account holder.
          readOnly: true
        assetCode:
          type: string
          description: >-
            The asset code of the account. This SHOULD be an ISO4217 currency
            code.
          example: USD
          readOnly: true
        assetScale:
          type: integer
          description: The scale of the account.
          example: 2
          readOnly: true
        authServer:
          type: string
          format: uri
          description: >-
            The URL of the authorization server endpoint for getting grants and
            access tokens for this account.
          readOnly: true
    incoming-payment:
      title: Incoming Payment
      description: >-
        An **incoming payment** resource represents a payment that will be, is
        currently being, or has been received by the account.
      type: object
      properties:
        id:
          type: string
          format: uri
          description: The URL identifying the incoming payment.
          readOnly: true
        accountId:
          type: string
          format: uri
          description: The URL of the account this payment is being made into.
          readOnly: true
        state:
          type: string
          description: The state of the payment as described above.
          enum:
            - pending
            - processing
            - completed
            - expired
          example: completed
          default: pending
        incomingAmount:
          $ref: "#/components/schemas/amount"
        receivedAmount:
          $ref: "#/components/schemas/amount"
        expiresAt:
          type: string
          description: >-
            The date and time when payments into the incoming payment will no
            longer be accepted.
        description:
          type: string
          description: >-
            Human readable description of the incoming payment that will be
            visible to the account holder.
        externalRef:
          type: string
          description: >-
            A reference that can be used by external systems to reconcile this
            payment with their systems. E.g. An invoice number. (Optional)
        ilpApddress:
          type: string
          description: The ILP address to use when establishing a STREAM connection.
          readOnly: true
        sharedSecret:
          type: string
          description: The shared secret to use when establishing a STREAM connection.
          readOnly: true
        receiptsEnabled:
          type: boolean
          description: True if the underlying STREAM has receipts enabled.
      examples:
        - id: "http://openpayments.example/incoming-payments/87562464512"
          accountId: "http://openpayments.example"
          state: completed
          incomingAmount:
            amount: 2500
            assetCode: USD
            assetScale: 2
          receivedAmount:
            amount: 2500
            assetCode: USD
            assetScale: 2
          expiresAt: "2022-02-03T23:20:50.52Z"
          description: Thanks for the coffee. Mo
          receiptsEnabled: true
    outgoing-payment:
      title: Outgoing Payment
      description: >-
        An **outgoing payment** resource represents a payment that will be, is
        currently being, or has previously been, sent from the account.
      type: object
      properties:
        id:
          type: string
          format: uri
          description: The URL identifying the incoming payment.
          readOnly: true
        accountId:
          type: string
          format: uri
          description: The URL of the account this payment is being made into.
          readOnly: true
        state:
          type: string
          description: The state of the payment as described above.
          enum:
            - pending
            - processing
            - completed
            - expired
            - failed
          example: completed
          default: pending
        authorized:
          type: boolean
          description: Indicates if the payment is authorized to begin processing.
          default: false
        receivingAccount:
          type: string
          format: uri
          description: The URL of the account that is being paid.
        receivingPayment:
          type: string
          format: uri
          description: The URL of the incoming payment that is being paid.
        receiveAmount:
          $ref: "#/components/schemas/amount"
        sendAmount:
          $ref: "#/components/schemas/amount"
        fundsAvailable:
          type: boolean
          description: >-
            Indicates that there are funds available in the underlying account
            to complete this payment. This is not a guarantee they will still be
            available when the payment is attempted but it is a good indicator
            to a client that it should attempt to authorize the payment.
          readOnly: true
        expiresAt:
          type: string
          description: >-
            The date and time when the calculated `sendAmount` is no longer
            valid.
          readOnly: true
        description:
          type: string
          description: >-
            Human readable description of the outgoing payment that will be
            visible to the account holder and shared with the receiver.
        externalRef:
          type: string
          description: >-
            A reference that can be used by external systems to reconcile this
            payment with their systems. E.g. An invoice number. (Optional)
        receiptsEnabled:
          type: boolean
          description: True if the underlying STREAM has receipts enabled.
    amount:
      title: Amount
      type: object
      description: >-
        All amounts in open payments are represented as an unsigned 64-bit
        integer amount and an asset code and scale.


        The `assetCode` is a code that indicates the underlying asset. In most
        cases this SHOULD be a 3-character ISO 4217 currency code.


        The `assetScale` indicates how the value of `amount` has been scaled
        relative to the natural scale of the asset. For example, an `amount` of
        `1234` with an `assetScale` of `2` represents an amount of `12.34`.
      properties:
        amount:
          type: integer
          description: The amount that must be paid into the receiverâ€™s account.
          example: 250
          maximum: 18446744073709552000
          minimum: 0
        assetCode:
          type: string
          description: >-
            The asset code of the amount. This SHOULD be an ISO4217 currency
            code.
          example: USD
        assetScale:
          type: integer
          description: The scale of the amount.
          example: 2
      examples:
        - amount: 2500
          assetCode: USD
          assetScale: 2
        - amount: 500
          assetCode: EUR
          assetScale: 2
        - amount: 123456789
          assetCode: BTC
          assetScale: 8
  securitySchemes:
    GNAP:
      name: Authorization
      type: apiKey
      in: header
      description: >-
        The API uses the Grant Negotiation and Authorization Protocol for
        authorization. An access token must be acquired from an authorization
        server before accessing the API and then provided in the request headers
        using the prefix `GNAP`.


        All requests must also be signed using a client key over some select
        headers and a digest of the request body.
  responses:
    "401":
      description: Authorization required
      headers:
        WWW-Authenticate:
          schema:
            type: string
          description: >-
            The address of the authorization server for grant requests in the
            format `GNAP as_uri=<URI>`
    "403":
      description: Forbidden
security:
  - GNAP: []
